### ISSUE TITLE
Missing license statement

### ISSUE THREAD

**Issue by chrish42** [kiffie/pic32-rs#1]
Super happy to see packages to program on PIC32 with Rust. Would you mind adding a license statement, though? Preferably the same as Rust (Apache2 & MIT) for your code, and whatever the license from Microchip's code is.

I'd love for this to eventually grow into official Rust embedded support for PIC32, but clear licenses are a prerequisite on that journey. Otherwise, thanks again!

**Comment by kiffie** [comment]
Supper happy to see that there is some interest in using Rust on the PIC32 devices. The idea is indeed to make the code available under a permissive OSS license. I added ```"MIT OR Apache-2.0"``` to the ```Cargo.toml``` files.
