### ISSUE TITLE
Blinky not blinking

### ISSUE THREAD

**Issue by RobertGauld** [kiffie/pic32-rs#17]
Hi, I came here from mygnu's blog at https://gill.net.in/posts/pic32-blink-led-rust/ and can't get blinky to blink. I think I've done everything I should - have I missed a step somewhere?

I'm using a PICkit3, with the firmware updated as per https://github.com/sergev/pic32prog/wiki/Using-PICkit3.
The wiring on the breadboard has been double checked, and a simple blinky program made with MPlabX and uploaded using pic32prog correctly blinks the LED on pin 14.

I'm using nightly, and have updated memory.x to reflect that I'm using a PIC32MX270F256B-50I/SP, the code builds and converts to hex without displaying errors.

diff memory.x:
```diff
index 368212b..e9049d9 100644
--- a/examples/blinky/memory.x
+++ b/examples/blinky/memory.x
@@ -14,8 +14,8 @@ PROVIDE(_ebase_address = 0x9D000000);  /* first 4 KiB of prog$
 MEMORY
 {
     boot_flash          (rx)    : ORIGIN = 0xBFC00000, LENGTH = 3k - 0x10
-    program_flash       (rx)    : ORIGIN = 0x9D000000, LENGTH = 128k
-    sram                (w!x)   : ORIGIN = 0x80000000, LENGTH = 32k
+    program_flash       (rx)    : ORIGIN = 0x9D000000, LENGTH = 256k
+    sram                (w!x)   : ORIGIN = 0x80000000, LENGTH = 64k
     configsfrs                  : ORIGIN = ORIGIN(boot_flash) + LENGTH(boot_fl$
 }


```

Steps I'm taking to compile/upload:
```
cargo build --release
cargo objcopy --release -- -O ihex blinky.hex
pic32prog -p blinky.hex
```

Output from pic32prog:
```
Programmer for Microchip PIC32 microcontrollers, Version 2.0.204
    Copyright: (C) 2011-2015 Serge Vakulenko
      Adapter: PICkit3 Version 2.0.5
    Processor: MX270F256B
 Flash memory: 256 kbytes
  Boot memory: 3 kbytes
         Data: 5768 bytes
        Erase: done
Program flash: ####################################################### done
 Verify flash: ###################################################### done
 Program rate: 406 bytes per second
``

**Comment by RobertGauld** [comment]
The generated hex file.
[blinky.zip](https://github.com/user-attachments/files/16451096/blinky.zip)

**Comment by kiffie** [comment]
Hi, I tried your hex file and it indeed does not work on a MX270 device that I put on a breadboard. When I compile the blinky example, I get a different hex file that works (blinking and UART output). Not clear why your hex file does not work.

You could try to have a look at the listing
```sh
    rust-objdump -Sdt target/mipsel-unknown-none/release/blinky
```

Or maybe is there another cargo config files in some directory that does strange things?

**Comment by RobertGauld** [comment]
Thanks, that's annoying I'd really hoped it was an obvious stupid thing I'd done.

No more cargo config files between your repositroy and the root. Only changes in ~/.cargo have been lint settings.

I lack the experience to use the objdump file but I'm assuming "file format elf32-mips", and that there's something at both 0xBFC00000 and 0x9D000000 is good.

In an attempt to confirm that I'd done something stupid on my system I used a docker container to get a build and gained a different but still failing hex file.

``
FROM rustlang/rust:nightly
COPY . /blinky
RUN rustup component add rust-src && cargo install cargo-binutils && rustup component add llvm-tools-preview
RUN cd /blinky && cargo build --release && cargo objcopy --release -- -O ihex docker-test.hex && rust-objdump -Sdt target/mipsel-unknown-none/release/blinky > docker-objdump
```
[docker-hex.zip](https://github.com/user-attachments/files/16472764/docker-hex.zip)
[docker-objdump.zip](https://github.com/user-attachments/files/16472765/docker-objdump.zip)
[objdump.zip](https://github.com/user-attachments/files/16472766/objdump.zip)

**Comment by kiffie** [comment]
Still cannot reproduce the problem. I built a container image using the following Containerfile.

```Containerfile
FROM docker.io/rustlang/rust:nightly
RUN git clone https://github.com/kiffie/pic32-rs.git
RUN rustup component add rust-src && cargo install cargo-binutils && rustup component add llvm-tools-preview
RUN cd pic32-rs/examples/blinky && cargo build --release && cargo objcopy --release -- -O ihex docker-test.hex && rust-objdump -Sdt target/mipsel-unknown-none/release/blinky > docker-objdump
```

I used podman instead of docker, but this should not matter. When I build the image and then flash the hex file extracted from that image, I get a blinking LED. Not clear to me what's going on. Maybe, I will try on a different host although this should not make any difference.

**Comment by kiffie** [comment]
I built it on a fresh Debian12 + podman. It blinks on a 32MX270F256B-50I/SP installed on a breadboard. Here is the hex file.
[docker-test.hex.zip](https://github.com/user-attachments/files/16479360/docker-test.hex.zip)

**Comment by RobertGauld** [comment]
Thank you, when your hex file didn't work it pointed in in the direction of the programmer.
It turns out that the version of pic32prog I was using was too old, resolved by building the latest version.
