### ISSUE TITLE
Real Time Operating System

### ISSUE THREAD

**Issue by MohammedMaarof** [kiffie/pic32-rs#7]
Will there be any support for RTOS e.g. freeRTOS anytime soon?

**Comment by kiffie** [comment]
FreeRTOS might be an option. I had a look at the [FreeRTOS-rust](https://github.com/lobaro/FreeRTOS-rust) crate some time ago. But I did not try it. There is a FreeRTOS port for the PIC32. So, in theory, it should be easy to implement support for it.

Any real interest in trying this?

**Comment by MohammedMaarof** [comment]
I'm just exploring about rust and came across xRTOS support.

Thank you for sharing!
